```{r echo=FALSE,results='hide',message=FALSE,warning=FALSE,error=FALSE}
library(RMySQL)
library(plyr)
opts_chunk$set(echo=FALSE,results='hide',message=FALSE,warning=FALSE,error=FALSE)
```

# Contribution on Firefox for Android

This report was generated by a [knitr](http://yihui.name/knitr/) script that uses bug reports extracted using the [Bicho tool](http://metricsgrimoire.github.io/Bicho/) to compute contributor metrics. The source code can be found at <https://github.com/rodrigorgs/mozilla-contributors>.

```{r cache=TRUE}
# Loading

con <- dbConnect(MySQL(), user="root", password="root", dbname="bugs_mozilla", host="localhost")

query <- "SELECT 
  issue AS bug, type AS bug_severity, summary AS short_desc, 
  status as bug_status, resolution AS resolution, priority AS priority,
  submitted_by AS reporter, submitted_on AS creation_ts,
  assigned_to AS assigned_to, delta_ts, target_milestone
  FROM issues iss
  INNER JOIN issues_ext_bugzilla ieb ON ieb.id = iss.id"

bugs <- dbGetQuery(con, query)

query <- "SELECT bug.issue AS bug, act.changed_by AS user, 
  act.changed_on as time, act.field AS field, act.old_value AS previousvalue,
  act.new_value AS currentvalue
  FROM changes act
  INNER JOIN issues bug ON act.issue_id = bug.id"

events <- dbGetQuery(con, query)
events$time <- as.POSIXct(events$time, format="%Y-%m-%d %H:%M:%S")
events$field <- tolower(events$field)

dbDisconnect(con)
```

```{r cache=TRUE}
# Filtering
review.requests <- subset(events, substring(field, 1, 10) == "attachment" & substring(currentvalue, 1, 7) == "review?")
data <- merge(review.requests, bugs)
data <- subset(data, resolution == "FIXED" & target_milestone != "---" & target_milestone != "Future")
 
tab <- table(data$user, data$target_milestone)
tab <- as.data.frame.matrix(tab)
punch.card <- (tab > 0)
```

```{r results='markup'}
# Contributors by release
contributors.per.release <- apply(punch.card, 2, sum)
#par(las=2); barplot(contributors.per.release, main="Contributors per release")
# First-time contributors
first.time <- apply(punch.card, 1, function(v) v & !duplicated(v))
first.time.contributors.per.release <- apply(first.time, 1, sum)
#par(las=2); barplot(first.time.contributors.per.release, main="First-time contributors per release")
##############
# Plot: Contributors per release (absolute)
x <- cbind(contributors.per.release, first.time.contributors.per.release)
x[, 1] <- x[, 1] - x[, 2]
colors <- c("brown", "darkgreen")
par(las=2); barplot(t(x), main="Contributors per release", col=colors); legend("bottomright", legend=c("recurrent contributors", "new contributors"), fill=colors, bg="white")
###########
# Plot: Contributors per release (%)
x <- cbind(contributors.per.release, first.time.contributors.per.release)
x[, 2] <- 100 * x[, 2] / x[, 1]
x[, 1] <- 100 - x[, 2]
barplot(t(x), main="Contributors per release (%)", col=colors); legend("bottomright", legend=c("recurrent contributors", "new contributors"), fill=colors, bg="white")
```

```{r results='markup'}
# Contributor "age" per release
releases.contributed.by.user <- apply(punch.card, 1, cumsum)
age <- apply(releases.contributed.by.user, 1, function(v) mean(v[v > 0]))
par(las=2); barplot(age, main="Average contributor experience\n(in number of releases they contributed to)")
```
